server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: mi-data-service

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    user:
      name: admin
      password: 123456
  profiles:
    active: dev

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.marathon.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


# JWT配置
jwt:
  secret: marathon-information's-secret-key
  expiration: 86400000  # 24小时
  header: Authorization
  token-start-with: Bearer 
# spring security

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: 
    enable-home-custom: false
    home-custom-path: classpath:markdown/home.md
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2024 Marathon
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  basic:
    enable: false
    username: admin
    password: admin